version: '3.7'

services:
  django-server:
#    restart: always
    build:
      context: .
      dockerfile: ./docker/django-server/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: apps.production
    expose:
      - "8000"
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app
      - "staticdata:/var/www/csv_search_diff/static/"
      - "/var/log/csv_search_diff/:/var/log/"
      # - "~/Projects/logs/csv_search_diff/:/var/log/"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --clear --noinput && gunicorn config.wsgi -b 0.0.0.0:8000"
    container_name: server-csv_search_diff

  nginx:
#    restart: always
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - django-server
    volumes:
      - "./docker/nginx/:/etc/nginx/"
      - "staticdata:/var/www/static/"
      - "/var/log/csv_search_diff/:/var/log/nginx/"
      # - "~/Projects/logs/csv_search_diff/:/var/log/nginx/"
    container_name: nginx-csv_search_diff

volumes:
  staticdata: