"""
Django settings for csv_search_diff project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from .base import *
from pathlib import Path

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# 開発用のログ設定
LOGGING = {
    # バージョンは'1'固定
    'version': 1,
    # 既存のログは無効化しない
    'disable_existing_loggers': False,
    # ログフォーマット7Ω
    'formatters': {
        # 開発用
        'develop': {
            'format': '%(asctime)s [%(levelname)s] %(pathname)s:%(lineno)d'
                      '%(message)s '
        },
    },
    # ハンドラ
    'handlers': {
        # ファイル出力用ハンドラ
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'develop',
        }
    },
    # ロガー
    'loggers': {
        # 自作アプリケーション用ロガー
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False
        },
        # Django本体のロガー
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False
        },
    },
}

